### ISSUE TITLE
Server side crash because of vein miner version1.4.4

### ISSUE THREAD

**Issue by papamaionise** [PrincessCyanMarine/SimpleVeinminer#17]
![Screenshot (1264)](https://github.com/PrincessCyanMarine/SimpleVeinminer/assets/126779287/f8315724-af71-4e93-adc3-585966237613)

works on singleplayer

but crashes the server

**Comment by papamaionise** [comment]
its crashes just how it used to crash with old version for older fabric modloader

**Comment by papamaionise** [comment]
https://mclo.gs/7hrwtS0

**Comment by Flakkas** [comment]
I have the same problem, everything was fine for me and my friends untill I updated fabric for my server. (from 0.14.23 to 0.15.0 I believe)A shame as this is my preferred veinminer mod

**Comment by PrincessCyanMarine** [comment]
I'm very sorry

I actually thought I had uploaded a fix like a week ago, but it seems I forgot to
The problem was with one of the libraries I was using

Unfortunately, because of certain circunstances, I can't currently update the mod and won't be able to until at least next week


If you are willing to build the mod yourself, the ["1.20.1-backport" branch](https://github.com/PrincessCyanMarine/SimpleVeinminer/tree/1.20.1-backport) should already have the fix (even the version is updated, if you look at gradle.properties)

(if you do want to do that, [https://fabricmc.net/wiki/tutorial:setup](https://fabricmc.net/wiki/tutorial:setup) should help. But of course using my mod instead of the example one)

**Comment by PrincessCyanMarine** [comment]
(also, I recommend using IntelliJ IDEA. Just open the folder with it, wait for a bit close and open again, then open the gradlew tab on the right and look for "build". Then a .jar should appear on ./build/libs)

**Comment by papamaionise** [comment]
> I'm very sorry
> 
> I actually thought I had uploaded a fix like a week ago, but it seems I forgot to The problem was with one of the libraries I was using
> 
> Unfortunately, because of certain circunstances, I can't currently update the mod and won't be able to until at least next week
> 
> If you are willing to build the mod yourself, the ["1.20.1-backport" branch](https://github.com/PrincessCyanMarine/SimpleVeinminer/tree/1.20.1-backport) should already have the fix (even the version is updated, if you look at gradle.properties)
> 
> (if you do want to do that, https://fabricmc.net/wiki/tutorial:setup should help. But of course using my mod instead of the example one)

I can wait take your time good to know that you'll fix it because there really no other fabric mods like this one

**Comment by PrincessCyanMarine** [comment]
Just uploaded version 1.4.5 to curseforge ([https://www.curseforge.com/minecraft/mc-mods/simple-veinminer/files/5030227](https://www.curseforge.com/minecraft/mc-mods/simple-veinminer/files/5030227))

It worked on my test server, but can you confirm whether it works on yours?

**Comment by Flakkas** [comment]
By chance I was just on my server as you answered. I updated the mod and everything seems to work wonderfully. Many thanks!

**Comment by PrincessCyanMarine** [comment]
Ok, nice

Thank you both for using my mod 
And sorry for taking so long to fix the issue

Have fun~
