### ISSUE TITLE
A couple of ideas

### ISSUE THREAD

**Issue by DanFromDiscord** [PrincessCyanMarine/SimpleVeinminer#19]
First of I want to say thank you, and well done on this mod. I've been looking for an alternative to FTB Ultimine and this seems to be it. 

And on that note, I would like to suggest two things to be added/changed. 

- One of the main reasons I liked Ultimine so much was its ability to clear out grass effortlessly. I believe it did that by checking for matching blocks in a larger radius than normal, say 2-3 diagonals instead of 1, and also by treating all kinds of ground foliage as the same when vein mining.
- Displaying how many blocks will be mined. This is probably the least important addition, but it wouldn't hurt to have. Especially when you can't see all the blocks you want to mine, while also being unsure if anything is connected that you don't want to be mined. I've had this happen a few times now and while it's not completely devastating, it is an avoidable setback.

Hope you consider these things and work on them at your own pace. Having a great vein mining mod is more than enough for me either way. 😄

**Comment by PrincessCyanMarine** [comment]
Great ideas!
I'll do my best to include them in the next update

(tho, I can't promise when that will be)

**Comment by PrincessCyanMarine** [comment]
1.4.6 added the "max radius" config as well as the "decrease radius" and "increase radius" keybindings
Change the config in order to determine how large the radius can be (up to 5, but larger than 3 lags on my computer. You'll have to try and see what works for yours) and then use the keybindings to change the radius on the fly

So you can keep it at 1 and then raise it when trying to break leaves (configurations for different blocks defaulting to different radiuses is not planned, but also not off the table)

**Comment by PrincessCyanMarine** [comment]
1.4.6 also adds a hud element that shows an icon of the block being veinmined as well as how many blocks are going to be broken

It can be repositioned and the icon and count can be individually turned off, however they cannot be detached from each other (the spacing between them can be adjusted, however)
